INSERT INTO board_tb(author, title, content) VALUES ('Kenneth', '제목1', '내용1');
INSERT INTO board_tb(author, title, content) VALUES ('Minsu', '제목2', '내용2');
INSERT INTO board_tb(author, title, content) VALUES ('Kim', '제목3', '내용3');
INSERT INTO board_tb(author, title, content) VALUES ('Denny', '제목4', '내용4');
INSERT INTO board_tb(author, title, content) VALUES ('Yongju', '제목5', '내용5');
INSERT INTO board_tb(author, title, content) VALUES ('Lee', '제목6', '내용6');
INSERT INTO board_tb(author, title, content) VALUES ('Jaehyung', '제목7', '내용7');
INSERT INTO board_tb(author, title, content) VALUES ('Jeong', '제목8', '내용8');
INSERT INTO board_tb(author, title, content) VALUES ('Psick', '제목9', '내용9');
INSERT INTO board_tb(author, title, content) VALUES ('Univ', '제목10', '내용10');
INSERT INTO board_tb(author, title, content) VALUES ('Metacomedy', '제목11', '내용11');
INSERT INTO board_tb(author, title, content) VALUES ('Lee', '제목12', '내용12');
INSERT INTO board_tb(author, title, content) VALUES ('Kenneth', '제목13', '내용14');
INSERT INTO board_tb(author, title, content) VALUES ('Minsu', '제목15', '내용15');
INSERT INTO board_tb(author, title, content) VALUES ('Kim', '제목16', '내용16');
INSERT INTO board_tb(author, title, content) VALUES ('Lee', '제목17', '내용17');
INSERT INTO board_tb(author, title, content) VALUES ('Yongju', '제목19', '한바퀴 돌 수 있다.');
INSERT INTO board_tb(author, title, content) VALUES ('Denny', '한바퀴 돌 수 있다', '-사무엘존슨-');
INSERT INTO board_tb(author, title, content) VALUES ('Kim', '하루에 3시간을 걸으면', '7년 후에 지구를');
INSERT INTO board_tb(author, title, content) VALUES ('Minsu', '이미 늦었을지 몰라도', '이제라도 무해하고 싶어');
INSERT INTO board_tb(author, title, content) VALUES ('Kenneth', '누구도 상처주지 않게', '정신차리고 살아야지');